---
- name: Act on webhook events
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Execute say-hello.yml playbook
      condition: event.payload.message == "Ansible is super cool"
      action:
        run_playbook:
          name: say-hello.yml
